language: rust
cache: cargo
os: linux
dist: bionic
arch:
  - arm64
  - ppc64le
  - s390x
rust:
  - stable
before_cache: |
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - cargo install cargo-tarpaulin
before_script: |
  - rustup component add rustfmt
script:
  - cargo clean
  - cargo build --verbose
  - cargo test --verbose
after_success: |
  - cargo tarpaulin --out Xml
  - curl -s https://codecov.io/bash | bash -s - -t 2492415e-6701-4af7-8d7a-7d01dbd80f29
