language: rust
cache: cargo
os: linux
dist: bionic
arch:
  - arm64
  - s390x
services:
  - postgresql
rust:
  - nightly
before_cache: |
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - cargo install cargo-tarpaulin
before_script:
  - rustup component add rustfmt
script:
  - echo DATABASE_URL=postgres://postgres@localhost/proc_server_test > .env
  - cargo install diesel_cli --no-default-features --features "postgres"
  - (cd page_backend && diesel setup)
  - cargo clean
  - cargo build
  - cargo test
  - cargo fmt --all -- --check
after_success: |
  - cargo tarpaulin --out Xml
  - curl -s https://codecov.io/bash | bash -s - -t 2492415e-6701-4af7-8d7a-7d01dbd80f29
