apiVersion: apps/v1

kind: Deployment

metadata:
  name: page-frontend-deployment
  labels:
    app: page-frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-frontend-pod

  template:
    metadata:
      name: page-frontend-pod
      labels:
        app: page-frontend-pod

    spec:
      containers:
        - name: page-frontend-container
          image: page_ui
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"                   