name: Database Integration Test
on: [push]
jobs:
  Database-Integration-Action:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-name:
          - procserver
        db-user:
          - procserver
        db-password:
          - procserver
        db-host:
          - localhost
        db-port:
          - 5432

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ matrix.db-name }}
          POSTGRES_USER: ${{ matrix.db-user }}
          POSTGRES_PASSWORD: ${{ matrix.db-password }}
        ports:
          - ${{ matrix.db-port }}:${{ matrix.db-port }}
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        env:
          DATABASE_URL: postgresql://${{ matrix.db-user }}:${{ matrix.db-password }}@${{ matrix.db-host }}:${{ matrix.db-port }}/${{ matrix.db-name }}?schema=public
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
